stages:
  - test
  - build
  - build-variant
  - release

default:
  image: docker:stable
  tags:
    - docker
  services:
    - docker:dind

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

variables:
  DOCKER_HOST: tcp://docker:2375/
  PANDOC_VERSION: '2.18'

test:pandoc:
  stage: test
  needs: []
  before_script: []
  services: []
  image: hadolint/hadolint:latest-alpine
  script:
    - hadolint Dockerfile

test:eisvogel:
  stage: test
  needs: []
  before_script: []
  services: []
  image: hadolint/hadolint:latest-alpine
  script:
    - hadolint variants/eisvogel.Dockerfile

build:pandoc:
  stage: build
  needs: ["test:pandoc"]
  script:
    - docker pull "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}" || echo "could not pull image for use as cache"
    - docker build --cache-from "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}" --build-arg PANDOC_VERSION="$PANDOC_VERSION" -t "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}" .
    - docker push "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}"

build-variant:eisvogel:
  stage: build-variant
  needs: ["build:pandoc", "test:eisvogel"]
  script:
    - docker pull "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}-eisvogel" || echo "could not pull image for use as cache"
    - docker build --cache-from "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}-eisvogel" --build-arg PANDOC_VERSION="$PANDOC_VERSION" -t "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}-eisvogel" ./variants -f ./variants/eisvogel.Dockerfile
    - docker push "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}-eisvogel"

release:pandoc:
  stage: release
  needs: ["build:pandoc"]
  script:
    - docker pull "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}"
    - docker tag "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}" "${CI_REGISTRY_IMAGE}:latest"
    - docker push "${CI_REGISTRY_IMAGE}:latest"
  only:
    - main
    - tags

release:eisvogel:
  stage: release
  needs: ["build-variant:eisvogel"]
  script:
    - docker pull "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}-eisvogel"
    - docker tag "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}-eisvogel" "${CI_REGISTRY_IMAGE}:eisvogel"
    - docker push "${CI_REGISTRY_IMAGE}:eisvogel"
  only:
    - main
    - tags

release:rpm:
  stage: release
  needs: ["build:pandoc"]
  script:
    - "id=$(docker create ${CI_REGISTRY_IMAGE}:${PANDOC_VERSION} ls) && docker cp $id:/root/pandoc.rpm - > pandoc-${PANDOC_VERSION}.rpm"
    - "apk add --no-cache curl"
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file pandoc-${PANDOC_VERSION}.rpm "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pandoc-rpm/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}.rpm"'
  only:
    - tags
  artifacts:
    paths:
      - "*.rpm"

