stages:
  - test
  - build
  - build-variant
  - release

services:
  - docker:dind

image: docker:stable

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

variables:
  DOCKER_HOST: tcp://docker:2375/
  PANDOC_VERSION: '2.11.1.1'

test:pandoc:
  before_script: []
  image: hadolint/hadolint:latest-alpine
  script:
    - hadolint Dockerfile

test:eisvogel:
  before_script: []
  image: hadolint/hadolint:latest-alpine
  script:
    - hadolint eisvogel/Dockerfile

build:pandoc:
  stage: build
  tags:
    - docker
  script:
    - docker pull "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}" || echo "could not pull image for use as cache"
    - docker build --cache-from "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}" --build-arg PANDOC_VERSION="$PANDOC_VERSION" -t "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}" .
    - docker push "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}"

build-variant:eisvogel:
  stage: build-variant
  tags:
    - docker
  script:
    - docker pull "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}-eisvogel" || echo "could not pull image for use as cache"
    - docker build --cache-from "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}-eisvogel" --build-arg PANDOC_VERSION="$PANDOC_VERSION" -t "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}-eisvogel" ./eisvogel/
    - docker push "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}-eisvogel"

release:pandoc:
  stage: release
  tags:
    - docker
  script:
    - docker pull "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}"
    - docker tag "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}" "${CI_REGISTRY_IMAGE}:latest"
    - docker push "${CI_REGISTRY_IMAGE}:latest"
  only:
    - master

release:eisvogel:
  stage: release
  tags:
    - docker
  script:
    - docker pull "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}-eisvogel"
    - docker tag "${CI_REGISTRY_IMAGE}:${PANDOC_VERSION}-eisvogel" "${CI_REGISTRY_IMAGE}:eisvogel"
    - docker push "${CI_REGISTRY_IMAGE}:eisvogel"
  only:
    - master

